# Generated by Django 2.0.5 on 2018-06-07 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_code', models.CharField(default=game.models.createUUID, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('players', models.IntegerField(default=0)),
                ('maxPlayers', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('round', models.IntegerField(default=0)),
                ('maxRounds', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(120)])),
                ('waitSeconds', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('playerPosition', models.IntegerField()),
                ('playing', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('playerState', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.GameState')),
            ],
        ),
        migrations.CreateModel(
            name='RoundState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('valid', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('deckNumber', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='game.Player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('onPlayerHand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onPlayerHand', to='game.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.GameState'),
        ),
        migrations.AddField(
            model_name='game',
            name='roundState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.RoundState'),
        ),
    ]
