# Generated by Django 2.0.5 on 2018-06-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180608_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='onPlayerHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onPlayerHand', to='game.Player'),
        ),
    ]
